apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: app1
spec:
  # Selector связывает этот Service с Pod'ами, у которых есть лейбл app: app1
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      # !!! ЭТО ВАЖНОЕ ИЗМЕНЕНИЕ: Используем переменную
      targetPort: {{ .Values.app1.servicePort }}
  type: ClusterIP    # Делает Service доступным только внутри кластера
