# 1. FROM — базовый образ
FROM nginx:latest

# 2. COPY — копируем наш конфиг внутрь контейнера
COPY default.conf /etc/nginx/conf.d/default.conf

# 3. EXPOSE — открываем порт для доступа снаружи
EXPOSE 8085
